# Process a single image pair with ISCE2
name: offset_pair
run-name: ${{ inputs.reference }}_${{ inputs.secondary }}

# Set workflow input parameters and defaults
on:
  workflow_dispatch:
      inputs:
        polygon:
          type: string
          required: true
          description: AOI WKT
          default: 'POLYGON ((38.6401149641734 -69.9149589283716,38.0950151069544 -70.0278414394631,39.3056438596154 -70.5135264611673,40.1296320158775 -70.3031189013304,38.6401149641734 -69.9149589283716))'
        reference:
          type: number
          required: true
          description: Reference Absolute Orbit
          default: 052893
        secondary:
          type: number
          required: true
          description: Secondary Reference Orbit
          default: 053418
        polarization:
          description: 'Polarization'
          required: false
          default: hh
          type: string
  
  # Must duplicate inputs for workflow_call (https://github.com/orgs/community/discussions/39357)
  workflow_call:
    inputs:
      polygon:
        type: string
        required: true
      reference:
        type: string
        required: true
      secondary:
        type: string
        required: true
      polarization:
        type: string
        required: false

jobs:
    topsApp:
      name: ${{ inputs.reference }}_${{ inputs.secondary }}
      runs-on: ubuntu-latest
      defaults:
        run:
            shell: bash -el {0}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Report Runner Specs
          run: | 
            lscpu 
            free -h 
            df -h

        # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        - name: Free up disk space
          run: |
            sudo apt clean
            sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
            df -h

        - name: Install Conda environment with Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            cache-environment: true
            environment-file: environment-burst2safe.yml

        # NOTE: not ideal. maybe use earthaccess python library?
        - name: Configure NASA & ESA NETRC
          env: 
            EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
            EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
            ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
            ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
          run: |
            echo "machine urs.earthdata.nasa.gov login $EARTHDATA_USERNAME password $EARTHDATA_PASSWORD" > ~/.netrc
            echo "machine dataspace.copernicus.eu login $ESA_USERNAME password $ESA_PASSWORD" >> ~/.netrc
            chmod 0600 ~/.netrc
        
        - name: Prepare ISCE2 TopsApp.py
          run: |
            ./scripts/burst2topsapp.py \
              --reference ${{ inputs.reference }} \
              --secondary ${{ inputs.secondary }} \
              --wkt "${{ inputs.polygon }}" \
              --pol ${{ inputs.polarization }} \

        - name: DEBUG
          run: |
            mkdir merged
            touch merged/filt_topophase.flat.geo.vrt

        # - name: Run ISCE2 TopsApp.py
        #   run: |
        #     export PATH=$PATH:$ISCE_HOME/applications
        #     topsApp.py 
        
        # NOTE: hardcoded south polar sterographic currently
        # Match Hyp3 conventions (https://github.com/relativeorbit/hyp3-isce2/blob/cb09db2a1b38fb940a43145d603b3fa18f834aab/src/hyp3_isce2/insar_tops_fufiters.py#L485)
        # TODO: turn this into a script
        - name: Convert Outputs
          run: |
            mkdir output
            cp topsApp.xml output
            gdalinfo --version

            # Amplitude and Wrapped Phase
            gdal_edit.py -a_nodata 0.0 merged/filt_topophase.flat.geo.vrt
            # gdal_calc.py --overwrite --outfile merged/filt_wrapped_phase.tif -A  merged/filt_topophase.flat.geo.vrt --calc "angle(A)" --type Float32 --format GTiff --NoDataValue=0 
            gdal_calc.py --overwrite --outfile merged/amplitude.tif -A merged/filt_topophase.flat.geo.vrt --calc "abs(A)" --type Float32 --format GTiff --NoDataValue=0 
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/filt_wrapped_phase.tif  output/filt_wrapped_phase.tif 
            gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/amplitude.tif output/amplitude.tif 

            # # Coherence
            # gdal_edit.py -a_nodata 0.0 merged/phsig.cor.geo.vrt
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/phsig.cor.geo.vrt output/phsig.cor.tif

            # # Offsets
            # gdal_translate -b 1 -a_nodata 0.0 merged/filt_dense_offsets.bil.geo.vrt merged/filt_dense_offsets.bil.geo.azi.vrt
            # gdal_translate -b 2 -a_nodata 0.0 merged/filt_dense_offsets.bil.geo.vrt merged/filt_dense_offsets.bil.geo.rng.vrt
            # gdal_edit.py -a_nodata 0.0 merged/dense_offsets_snr.bil.geo.vrt
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/filt_dense_offsets.bil.geo.azi.vrt output/filt_dense_offsets.azi.tif
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/filt_dense_offsets.bil.geo.rng.vrt output/filt_dense_offsets.rng.tif
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/dense_offsets_snr.bil.geo.vrt output/dense_offsets_snr.tif

            # # Geometry files
            # gdal_edit.py -a_nodata 0.0 merged/los.rdr.geo.vrt
            # gdal_calc.py --overwrite --outfile merged/lv_theta.tif -A merged/los.rdr.geo.vrt --A_band=1 --calc "(90-A)*pi/180" --type Float32 --format GTiff --NoDataValue=0 
            # gdal_calc.py --overwrite --outfile merged/lv_phi.tif -A merged/los.rdr.geo.vrt --A_band=2 --calc "(90+A)*pi/180" --type Float32 --format GTiff --NoDataValue=0 
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/lv_theta.tif output/lv_theta.tif 
            # gdalwarp -tap -tr 30 30 -t_srs EPSG:3031 -of COG merged/lv_phi.tif output/lv_phi.tif 

        - name: Report Runner Specs
          run: | 
            du -sh *
            free -h 
            df -h

        - name: Upload Merged Outputs
          uses: actions/upload-artifact@v4
          with:
            name: ${{ inputs.reference }}_${{ inputs.secondary }}
            path: |
              output